FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
# Esto evita que pip guarde una copia caché de los instaladores, ahorrando espacio
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]